build: debug github token check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,7 +41,10 @@ jobs:
       - name: Verify github token
         run: |
           set -e
-          curl -s -w '%{http_code}\n' -H "Authorization: token $TOKEN" https://api.github.com/
+          if [[ -z "$TOKEN" ]]; then
+            echo "::error::Token secret not found"
+            exit 1
+          fi
           ghStatus=$(curl -s -w '%{http_code}\n' -H "Authorization: token $TOKEN" https://api.github.com/ | tail -n 1)
           if [[ $ghStatus -ne 200 ]]; then
             echo "::error::GitHub token is expired or invalid"
